services:
  db:
    image: postgres:16
    container_name: anthurium-db
    environment:
      POSTGRES_DB: happyflowers
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
